### ISSUE TITLE
BUG: Incorrectly sending subscription cancellation error email.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-ccbill#11]
An email notifying the admin that cancelling the recurring subscription may have failed is being sent incorrectly. It seems to be occurring from both failed cancellations from the Cancel page and successful cancellations via webhook. There may be other cases where it's being sent incorrectly as well.

**Comment by JarrydLong** [comment]
This mail will either be sent if the request failed and didn't send back a 200 status code, or a 200 status with an OK response message. Unable to replicate this though. Logs below confirm that the request to CCBill successfully goes through: 

`[14-Apr-2020 22:29:44 UTC] OK`
`[14-Apr-2020 22:29:44 UTC] 200`
`[14-Apr-2020 22:29:44 UTC] "results" "-12"`

This was also mentioned in Issue #3 but if we can get more details on the setup/installation and environment to try and replicate the issue that would help.
