### ISSUE TITLE
Is this plugin complete yet?

### ISSUE THREAD

**Issue by kherolake** [strangerstudios/pmpro-ccbill#21]
Hi there,

I have read in the description that the plugin is not complete. is it still the case? i really need to integrate ccbill to my webiste.

Your help is much appreciated.

**Comment by JarrydLong** [comment]
Hi there, 

Thanks for reaching out and for your interest in using the CCBill add-on. 

Unfortunately the add-on isn't ready just yet. We've still got a few bug fixes that need to be merged in, and further testing needs to be done. 

Would you perhaps be interested in testing it out during a Beta testing phase? If so, please get in touch with our support team over at www.paidmembershipspro.com

**Comment by andrewlimaza** [comment]
You may use CCBill as it's functional but remains in Beta. If you have any further questions please reach out to our support team via www.paidmembershipspro.com/support.

Thank you for understanding.
