### ISSUE TITLE
Currency & Tax fields don't show after saving 

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-ccbill#26]
Steps to replicate: 

- Select CCBill as your chosen payment gateway
- Fill out your details and hit save
- The currency section will be empty (screenshot below)

![image](https://user-images.githubusercontent.com/8989542/109296946-d9f34580-7839-11eb-964e-24a892961631.png)

**Comment by andrewlimaza** [comment]
This has been resolved with the latest version, I cannot replicate it anymore.
