### ISSUE TITLE
Cancellation Email 

### ISSUE THREAD

**Issue by dabrem** [strangerstudios/pmpro-ccbill#3]
Testing:

When testing payments through ccbill everything works fine but I am receiving an email over and over again. The testing of payment works good and the user is changed to the member status they purchased.

But immediately after the test I start receiving this email over and over again:

===========
Cancellation of subscription id: ************106 may have failed. Check CCBill Admin to confirm cancellation
===========

Anyone know why I am receiving this email even though the user hasn't cancelled?

**Comment by ideadude** [comment]
Should be fixed now.
