### ISSUE TITLE
PMPRO_CCBILL_DEBUG not working

### ISSUE THREAD

**Issue by misfist** [strangerstudios/pmpro-ccbill#46]
**Describe the bug**
Debug flag isn't working.

As instructed on line 4, use `true` instead of `'log'` to indicate events should be logged.

Instructions state:

```
//set this in your wp-config.php for debugging
//define( 'PMPRO_CCBILL_DEBUG', true );
```

Code was looking for:
`PMPRO_CCBILL_DEBUG === "log"`

**To Reproduce**
1. Add `define( 'PMPRO_CCBILL_DEBUG', true );` to `./wp-config.php`
2. Check for `./wp-content/plugins/pmpro-ccbill/logs/ccbill_webhook.txt`
3. File not present

**Expected behavior**
When `define( 'PMPRO_CCBILL_DEBUG', true );` is set in `./wp-config.php`, log file should be present and logging incoming webhook event data.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by andrewlimaza** [comment]
The `PMPRO_CCBILL_DEBUG` logic is slightly different to other gateways but should still result in the same outcome as the other gateways.

Defining `PMPRO_CCBILL_DEBUG` to `true` would email the WordPress admin address, and setting it to `"log"` would create the log.

**Comment by andrewlimaza** [comment]
This has been resolved with the latest commit to dev.
