### ISSUE TITLE
BUG: "Next step: Set up your SSL certificate and payment gateway." in WordPress admin.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-ccbill#7]
When CCBill is set as the primary gateway, the "Next step: Set up your SSL certificate and payment gateway." is displayed on all PMPro settings pages.

**Comment by maximx86** [comment]
I've set up Stripe and I am getting the same error. Does not matter whether it's live or a test environment the plugin keeps throwing "Next step: Set up your SSL certificate and payment gateway" message constantly. Stripe only requires to set up a webhook, nothing more to configure. Agree, seems like a bug.

**Comment by ideadude** [comment]
Note that the Next Step message will show up if any of the core gateway settings are still blank. We were not able to recreate this. Closing, but please open with more info if you are still having issues. Thanks.

**Comment by gameznet** [comment]
please fix this bug, it is annoying and is easy to replicate if you use the payment gateways being suggested. I have SSL setup and mycred is configured fully as the payment gateway and I can confirm that this message is remaining on my site also. Clicking the link just takes you to the Payment Gateway settings which are complete.  It becomes confusing when you look back over settings in the future and respond repeatedly to this message forcing us to double check payment gateway repeatedly when it is all entered correct and complete.   (Note: it does go away if we switch to paypal website payments pro however we are using mycred as the gateway)
