### ISSUE TITLE
BUG/ENHANCEMENT: Webhook handler causes fatal errors when accessed directly.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-ccbill#9]
When accessing the webhook handler directly (e.g. https://example.com/wp-content/plugins/pmpro-ccbill/webhook.php ) the plugin causes fatal errors.

We should make sure WP is always loaded like we do in other IPN/webhook handlers:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/ipnhandler.php#L2-L9

**Comment by andrewlimaza** [comment]
This has been fixed and improved.
